services:
  - type: web
    name: mariadb-practica
    env: docker
    plan: free
    image: mariadb:latest
    autoDeploy: true
    envVars:
      - key: MARIADB_ROOT_PASSWORD
        value: alumnoroot
      - key: MARIADB_DATABASE
        value: practica_db
      - key: MARIADB_USER
        value: jimenez
      - key: MARIADB_PASSWORD
        value: alumno
